name: E2E on Chrome
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    # env:
    #   SPECFM_FATHOM_SITE_ID: ${{ secrets.SPECFM_FATHOM_SITE_ID }}
    #   SPECFM_FATHOM_CUSTOM_URL: ${{ secrets.SPECFM_FATHOM_CUSTOM_URL }}
    #   SIMPLECAST_V2_API_KEY: ${{ secrets.SIMPLECAST_V2_API_KEY }}
    steps:
      - name: Cache Next
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn run build
          start: yarn run start
          browser: chrome
