name: index content in search

on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://spec.fm/api/search?token={{secrets.SEARCH_INDEXING_TOKEN}}
